// <auto-generated />
using System;
using LaborControl.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaborControl.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251007091200_AddFlexibleTaskSystem")]
    partial class AddFlexibleTaskSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaborControl.API.Models.ControlPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("RfidChipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RfidChipId");

                    b.ToTable("ControlPoints");
                });

            modelBuilder.Entity("LaborControl.API.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LaborControl.API.Models.RfidChip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChipId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChipId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("RfidChips");
                });

            modelBuilder.Entity("LaborControl.API.Models.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControlPointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("ScheduledTimeEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ScheduledTimeStart")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskExecutionId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ControlPointId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TaskExecutionId1");

                    b.HasIndex("TaskTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("LaborControl.API.Models.TaskDeviation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualQualification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedQualification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsReported")
                        .HasColumnType("boolean");

                    b.Property<string>("JustificationComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskExecutionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasApproved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TaskExecutionId");

                    b.ToTable("TaskDeviations");
                });

            modelBuilder.Entity("LaborControl.API.Models.TaskExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControlPointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FlagEcartOcr")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagHorsMarge")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagOutOfRange")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagQuickEntry")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagSaisieDifferee")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagSaisieRapide")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagSuspiciousValue")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagValeurRepetee")
                        .HasColumnType("boolean");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ScheduledTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ControlPointId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScheduledTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskExecutions");
                });

            modelBuilder.Entity("LaborControl.API.Models.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlertOnMismatch")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUniversal")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalWarning")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequiredQualification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("LaborControl.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanApproveDeviations")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LaborControl.API.Models.ControlPoint", b =>
                {
                    b.HasOne("LaborControl.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborControl.API.Models.RfidChip", "RfidChip")
                        .WithMany()
                        .HasForeignKey("RfidChipId");

                    b.Navigation("Customer");

                    b.Navigation("RfidChip");
                });

            modelBuilder.Entity("LaborControl.API.Models.RfidChip", b =>
                {
                    b.HasOne("LaborControl.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LaborControl.API.Models.ScheduledTask", b =>
                {
                    b.HasOne("LaborControl.API.Models.ControlPoint", "ControlPoint")
                        .WithMany()
                        .HasForeignKey("ControlPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborControl.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborControl.API.Models.TaskExecution", "TaskExecution")
                        .WithMany()
                        .HasForeignKey("TaskExecutionId1");

                    b.HasOne("LaborControl.API.Models.TaskTemplate", "TaskTemplate")
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LaborControl.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlPoint");

                    b.Navigation("Customer");

                    b.Navigation("TaskExecution");

                    b.Navigation("TaskTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaborControl.API.Models.TaskDeviation", b =>
                {
                    b.HasOne("LaborControl.API.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LaborControl.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaborControl.API.Models.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaborControl.API.Models.TaskExecution", "TaskExecution")
                        .WithMany()
                        .HasForeignKey("TaskExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Customer");

                    b.Navigation("PerformedByUser");

                    b.Navigation("TaskExecution");
                });

            modelBuilder.Entity("LaborControl.API.Models.TaskExecution", b =>
                {
                    b.HasOne("LaborControl.API.Models.ControlPoint", "ControlPoint")
                        .WithMany()
                        .HasForeignKey("ControlPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborControl.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborControl.API.Models.ScheduledTask", "ScheduledTask")
                        .WithMany()
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LaborControl.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlPoint");

                    b.Navigation("Customer");

                    b.Navigation("ScheduledTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaborControl.API.Models.TaskTemplate", b =>
                {
                    b.HasOne("LaborControl.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LaborControl.API.Models.User", b =>
                {
                    b.HasOne("LaborControl.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LaborControl.API.Models.TaskTemplate", b =>
                {
                    b.Navigation("ScheduledTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
